input_polygons:
  # - datasets: 
  #     - bgt/bgt_waterdeel.sqlite
  #     - bgt/bgt_ondersteunendwaterdeel.sqlite
  #   uniqueid: gml_id
  #   lifting: Water
  #   height_field: relatievehoogteligging
  # - datasets: 
  #     - bgt/bgt_onbegroeidterreindeel.sqlite
  #   uniqueid: gml_id
  #   lifting: Terrain
  #   height_field: relatievehoogteligging
  # - datasets: 
  #     - bgt/bgt_wegdeel.sqlite
  #     - bgt/bgt_ondersteunendwegdeel.sqlite
  #   uniqueid: gml_id
  #   lifting: Road
  #   height_field: relatievehoogteligging
  - datasets: 
      - bgt/bgt_pand.sqlite
    uniqueid: gml_id
    lifting: Building
    height_field: relatievehoogteligging

lifting_options: 
  Building:
    height_roof: percentile-90
    height_floor: percentile-10
    lod: 1
  Terrain:
    simplification: 10
  Forest:
    simplification: 10
  Water:
    height: percentile-10
  Road:
    height: percentile-50
  Separation:
    height: percentile-80
  Bridge/Overpass:
    height: percentile-50

input_elevation:
  - datasets:
      - ahn3/ahn3_cropped_1.laz
      - ahn3/ahn3_cropped_2.laz
    omit_LAS_classes:
      - 1 # unclassified
    thinning: 0

options:
  building_radius_vertex_elevation: 3.0
  radius_vertex_elevation: 1.0
  threshold_jump_edges: 0.5

output: 
  format: CSV-BUILDINGS-MULTIPLE
  building_floor: false
  vertical_exaggeration: 0
